### ISSUE TITLE
stats command and rank command dont work

### ISSUE THREAD

**Issue by WsDoragon** [Rehkloos/valorant_Nightbot#1]
when I replace the fields with the userID, tag and select the command it show me a error
![image](https://user-images.githubusercontent.com/54647620/106100480-2e13e880-611b-11eb-9012-fe4b3fd6e959.png)
![image](https://user-images.githubusercontent.com/54647620/106100554-4e43a780-611b-11eb-9352-34a22ebd167a.png)

**Comment by Rehkloos** [comment]
@WsDoragon should be functioning fine now but with your command you need to remove "rehkloos" and "001" with your riot name and tag #
