### ISSUE TITLE
No longer pulling stats

### ISSUE THREAD

**Issue by Denegal** [Rehkloos/valorant_Nightbot#2]
After your most recent revert, No stats are being pulled. Using the new example on the readme (no region variable; name, tag, and command only), it just yells at you that **'&region=' parameter not defined!** If you include any region however, no stats are pulled at all.

**Comment by Rehkloos** [comment]
> After your most recent revert, No stats are being pulled. Using the new example on the readme (no region variable; name, tag, and command only), it just yells at you that **'&region=' parameter not defined!** If you include any region however, no stats are pulled at all.

are you pulling rank stats?

atm this is the syntax

```
How-To: $(urlfetch https://valorant-nightbot.herokuapp.com/valorant-stats.php?region=(Available regions: eu, ap, na, kr)&nick=(in-game name)&tag=(tag)&command=(stats,rank,tracker,time);

Example: $(urlfetch https://valorant-nightbot.herokuapp.com/valorant-stats.php?region=na&nick=Rehkloos&tag=001&command=rank);
```
